[colors.normal]
black = "#545454"
blue = "#7caea3"
cyan = "#93e0e3"
green = "#a8b665"
magenta = "#d3859b"
red = "#ea6962"
white = "#f9f5d7"
yellow = "#d8a656"

[colors.bright]
black = "#3c3836"
blue = "#45707a"
cyan = "#4b7a5d"
green = "#6c782e"
magenta = "#945e80"
red = "#c14a4a"
white = "#f9f5d7"
yellow = "#b37109"

[colors.primary]
background = "#222222"
foreground = "#F9F9F9"

[font]
size = 11.0
normal = {family = "Hack Nerd Font", style = "Regular"}
bold = {family = "Hack Nerd Font", style = "Bold"}
italic = {family = "Hack Nerd Font", style = "Italic"}
bold_italic = {family = "monospace", style = "Bold Italic"}

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 1

[env]
WINIT_X11_SCALE_FACTOR = "1.00"
